### ISSUE TITLE
Can't make star metal Tinkers Construct tools

### ISSUE THREAD

**Issue by mraof** [EnigmaticaModpacks/Enigmatica2ExpertSkyblock#589]
**Modpack version**
1.36a

**Issue**
Smelting star metal gives the JAOPCA fluid instead, same issue as https://github.com/NillerMedDild/Enigmatica2Expert/issues/1489

**Comment by NillerMedDild** [comment]
Huh, I thought I fixed that. I'm afraid I won't have time to update E2ES further, so this won't be fixed :/

**Comment by mraof** [comment]
Well, if anyone wants to fix it for themselves, edit JAOPCA.cfg and add `molten` to `moduleBlacklist` under `astral_starmetal`
