### ISSUE TITLE
Salt types are hidden in JEI

### ISSUE THREAD

**Issue by KMorris29** [EnigmaticaModpacks/Enigmatica2ExpertSkyblock#590]
**Modpack version**
1.36a

**Issue**
Pam's Harvestcraft and Immersive Tech's salt are not viewable in JEI, only Mekanism's is. This appears to be a duplicate of an issue that was fixed in the main E2E, see https://github.com/NillerMedDild/enigmatica2/issues/236

**Comment by NillerMedDild** [comment]
I'm afraid I won't have time to update E2ES further, so this won't be fixed. Sorry :(
