### ISSUE TITLE
Rocket not fueling

### ISSUE THREAD

**Issue by DasHeinzchen** [EnigmaticaModpacks/Enigmatica2ExpertSkyblock#592]
**Modpack version**
1.36

**Issue**
The Fueling Station of Advanced Rocketry is not fueling my assembled rocket. i pumped Oxygen into the Fueling Station but it won't fuel the rocket. The Fueling Station is linked to the Rocket Assembling Machine, of course.

**Comment by NillerMedDild** [comment]
Oxygen is not rocket fuel :)

**Comment by DasHeinzchen** [comment]
But it is written as such at the Questbook. At Advanced Rocketry : Rocket Fuel
And it is also accepted by the Fueling Station.

**Comment by NillerMedDild** [comment]
.. oh. My apologies 😄 I guess my memory is a bit rusty. I'm afraid E2ES wont receive more updates, unless a highly critical bug is found. I don't have time to maintain it :(
