### ISSUE TITLE
Cannot make Wood Chipping through breaking wood with a Wooden Hammer

### ISSUE THREAD

**Issue by Zarfouxx** [EnigmaticaModpacks/Enigmatica2ExpertSkyblock#593]
**Modpack version**
1.36a

**Issue**
When I break an Oak Tree with a Wooden Hammer it doesn't destroy the whole tree and doesn't give me Wood Chippings

**Comment by NillerMedDild** [comment]
Thanks for the report. I'm afraid E2ES wont receive more updates, unless a highly critical bug is found. I don't have time to maintain it :(
