### ISSUE TITLE
/dank/null doubling

### ISSUE THREAD

**Issue by Ralea2** [EnigmaticaModpacks/Enigmatica2ExpertSkyblock#594]
Hello,
if I open the /dank/null and first put in an item and then take the thing down from the /dank/nullstand and place it back up again, I can take the item out ... if I repeat the whole thing without putting the item in, an item comes out anyway ... so then i have 2

**Comment by NillerMedDild** [comment]
Thanks for the report. I'm afraid E2ES wont receive more updates, unless a highly critical bug is found. I don't have time to maintain it :(
