### ISSUE TITLE
Expert Recipes Not Loading

### ISSUE THREAD

**Issue by jojou114** [EnigmaticaModpacks/Enigmatica2ExpertSkyblock#601]
### Modpack Version

1.37

### Describe your issue.

There don't seem to be any expert-mode recipe changes in my game. Wood provides 4 planks, chest recipe is 8 planks, and all modded recipes that are supposed to be gated are standard.

### Latest Log

https://gist.github.com/jojou114/22e72d2e5a757f9de79c96cb7e529091

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Thanks for the report.

Are you certain you didn't modify the pack in any way? I see a ton of CraftTweaker errors on startup.

**Comment by Carionis** [comment]
Hey there, this issue has appeared for me as well. It might be related to the curseforge api, however... It works only intermittently if you don't use their own app (in my case GDLauncher) and the download of mods fails regularly.

I've tried redownloading and different versions (1.37 and 1.35 as that one worked for me before), but now the error persists. The crafttweaker recipes are replaced by vanilla ones.

**Comment by NillerMedDild** [comment]
Im afraid that's a GDLauncher issue, nothing we can do :(

**Comment by Carionis** [comment]
I wasn't suggesting that you have to do anything about curseforge or GDLauncher, I was just trying to offer a clue to future people like me who are having the same issue. And after confirming it with MultiMC: It is a GDLauncher-issue...
