### ISSUE TITLE
Can't use a clock / compass to make rich slag

### ISSUE THREAD

**Issue by Yisenayan** [EnigmaticaModpacks/Enigmatica2ExpertSkyblock#602]
### Modpack Version

1.37

### Describe your issue.

I tried to use sand and clock / compass to make rich slag in the  Induction Smelter , but soon I found that the clock / compass couldn't fit into the machine, and then I downloaded the  package again and found that it was the same, so I changed the receipe and submitted this issue.The sentence may be a little strange, it may be caused by the translation software.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Thanks for the report. Changing the quark config like this should fix it:
https://github.com/EnigmaticaModpacks/Enigmatica2Expert/commit/d5c59cee27b06c5017019e1b89b851392a7ae3e6

**Comment by Yisenayan** [comment]
ok，now it work,thanks.
