### ISSUE TITLE
ex compressum auto compressor compresses uranium ingot into ic2 uranium block (not supposed to be obtainable)

### ISSUE THREAD

**Issue by FuzzyD75** [EnigmaticaModpacks/Enigmatica2ExpertSkyblock#603]
### Modpack Version

1.37

### Describe your issue.

As the title says, when the uranium ingots (immersive engineering) go into the auto compressor they get compressed into ic2 uranium block. And then they are stuck as ic2 uranium that can't be used for most recipes and as reactor fuel until you smelt them.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Thanks for the report. Unfortunately, I don't have time to fix this.
