### ISSUE TITLE
The woodworking formula can’t be synthesized。

### ISSUE THREAD

**Issue by Radishlraq** [EnigmaticaModpacks/Enigmatica2ExpertSkyblock#604]
### Modpack Version

1.37

### Describe your issue.

Overclocked upgrade. JEI Formula’s good. When I make it in a woodworking machine, the formula is automatically added but it doesn’t show the composite, and it doesn’t work.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by NillerMedDild** [comment]
Thanks for the report. I'm afraid E2ES wont receive more updates, unless a highly critical bug is found. I don't have time to maintain it :(
