### ISSUE TITLE
Multiplayer user cannot walk on island they could previously walk on

### ISSUE THREAD

**Issue by Silik0n** [EnigmaticaModpacks/Enigmatica2ExpertSkyblock#613]
### Modpack Version

v1.90g

### Describe your issue.

A user that previously played on my island, upon loading the new update into our server, can now not go into the vicinity of my island without being moved to a "void world" (a place with no blocks and a forced camera perspective based on their last previous perspective).  When they first loaded into the world, they spawned on an island 1000 blocks away from the center of my island. ![](https://cdn.discordapp.com/attachments/871505292888780890/1151333430135631872/image.png)This void world has the same coordinates as their new island spawn (their new island is at the coordinates -1000, 97, 0 and the island they are trying to walk on is at -1000, 97, -1000). Upon my teleporting them to my island, they are sent to the "void world". In creative mode, they can freely walk around the island and interact with it via placing and breaking blocks and changing block states, like flipping a lever. The moment they go into survival, they are transported to the "void world" and their coordinates are set to that of their new home island that they spawned on upon joining . Upon rejoining while in the "void world" they were spawned back at their island. Giving the user operator powers and using the FTB "My Team" menu to let them be on my team does not let them walk on the island either. They are in the same dimension as I am, as they could fly over in creative mode. I believe this issue has to do with the "Void Island Control" mod.

Originally, when we first started playing on this server, I just teleported them over to the island and set their spawn at -1000, 97, -1000 and that worked fine.

This issue is occurring on a free Aternos server that was auto updated when the update was added to CurseForge.

### Latest Log

https://mclo.gs/r1bjUtc

### Have you modified the modpack?

No

### User Modifications

I am not sure if this counts as a "modification", however we did update our world with the new update which means the update may conflict with something in our server and cause it to break. (No mods or anything of the sort have been added to the server)

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

silik0n#0

**Comment by NielsPilgaard** [comment]
I believe the intended way to get other players to your island is to invite them:
![image](https://github.com/EnigmaticaModpacks/Enigmatica2ExpertSkyblock/assets/21295394/83a96d04-3d03-4b28-9118-806dc38ecf5d)

**Comment by Silik0n** [comment]
Thank you for your response! apparently my friend did not add the qualifier "island" before saying "/join" (they said "/join" instead of "/island join") upon being invited, and then they just told me "it didn't work". Thank you for your help and apologies for the needless issue!
