### ISSUE TITLE
can't make advanced metallurgical fabricator on server but can on single player

### ISSUE THREAD

**Issue by DoomSquirter** [EnigmaticaModpacks/Enigmatica2ExpertSkyblock#619]
### Modpack Version

1.90g

### Describe your issue.

I can't make the AMF on bisect server but I can in ssp

I compared the contents of ./config/modularmachinery/machinery and all files are identical server to local install

controller basically states that there's no structure.  I've built it properly using firewood etc.

I built it from memory in single player just like I did on server and it worked first try

### Have you modified the modpack?

Yes

### User Modifications

added AE2UEL from start of pack before world gen
added jei utilities
added ae network analyzer
added worldedit
none of these could be affecting this.  

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

DoomSquinter

**Comment by DoomSquirter** [comment]
so I tried adding the 4 blocks to my irradiant altar to make the starlight crafting altar and it too says structure not found.  

so I think something about mm is broken on my server and I've no clue how to diagnose what that may be.

**Comment by DoomSquirter** [comment]
I ran /mm-syntax and got this 
![image](https://github.com/EnigmaticaModpacks/Enigmatica2ExpertSkyblock/assets/19479809/895c4c25-a0c3-40c0-a60a-fa2b846d6d24)

**Comment by Discomanco** [comment]
I feel like I fixed this on E2E, might have forgotten to give E2ES that treatment

**Comment by Discomanco** [comment]
Ok, with Starlight Altar also broken, it might be something else.

A latest log pls

**Comment by DoomSquirter** [comment]
rebooted the server to get this since I figure you want to know the bootup messages

looking at the debug.log while waiting for server to come up, yeah, there are definately issues.

[latest.log](https://github.com/EnigmaticaModpacks/Enigmatica2ExpertSkyblock/files/14044661/latest.log)

**Comment by DoomSquirter** [comment]
rebooted server a couple times and tried the starlight crafter in single player.  only works in single player but not in server

it's pretty clear to me something is wrong with mm in general on the server and not the client

I've asked if anyone playing e2es is having this issue but no responses

ghatus isn't directly playing this version.  he's applied patches so it's not cut and dry as to whether the problem originated on my end or were part of the server package yet

again, let me know some files to compare local/server and I'll do that

**Comment by DoomSquirter** [comment]
so the machinery/variables directory was empty somehow (no clue)

copied from local to server the one file in there and everything's working again.

disco checked server files and file is in there so server pack is fine

no clue, wtf, gremlins. 

closing issue
